-- MySQL Script generated by MySQL Workbench
-- 03/06/19 06:32:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdce
-- -----------------------------------------------------
-- Base de datos de Consulta Externa

-- -----------------------------------------------------
-- Schema bdce
--
-- Base de datos de Consulta Externa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdce` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `bdce` ;

-- -----------------------------------------------------
-- Table `bdce`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdce`.`tipo_usuario` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdce`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdce`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `turno` VARCHAR(15) NOT NULL,
  `idtipo` INT NOT NULL,
  `condicion` TINYINT(1) NOT NULL DEFAULT 1,
  `fechaalta` DATE NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuarios_tipo_usuario1_idx` (`idtipo` ASC),
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`idtipo`)
    REFERENCES `bdce`.`tipo_usuario` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdce`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdce`.`consultas` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `curp` VARCHAR(18) NULL,
  `expediente` VARCHAR(10) NULL,
  `edad` INT(3) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `spss` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `prospera` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `migrante` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `indigena` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `discapacidad` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `primvez1` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `diagnostico1` VARCHAR(100) NOT NULL,
  `primvez2` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `diagnostico2` VARCHAR(100) NULL,
  `referido` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `contrareferido` VARCHAR(2) NOT NULL DEFAULT 'NO',
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idconsulta`),
  INDEX `fk_consultas_usuarios_idx` (`idusuario` ASC),
  CONSTRAINT `fk_consultas_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bdce`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
